-- Optional course folders. Existing courses remain valid with folder_id = NULL.
create table if not exists public.course_folders (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.courses
  add column if not exists folder_id bigint references public.course_folders(id) on delete set null;

alter table public.course_folders enable row level security;

drop policy if exists "course_folders_select_own" on public.course_folders;
drop policy if exists "course_folders_insert_own" on public.course_folders;
drop policy if exists "course_folders_update_own" on public.course_folders;
drop policy if exists "course_folders_delete_own" on public.course_folders;
create policy "course_folders_select_own" on public.course_folders for select using (auth.uid() = user_id);
create policy "course_folders_insert_own" on public.course_folders for insert with check (auth.uid() = user_id);
create policy "course_folders_update_own" on public.course_folders for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "course_folders_delete_own" on public.course_folders for delete using (auth.uid() = user_id);

-- Courses remain protected by their own owner; folder_id is optional and does not alter existing ownership.
