-- Persistent shared ordering for courses and optional course folders.
-- This migration does not alter or remove existing content.

-- Composite targets let PostgreSQL enforce that an ordered item belongs to
-- the same chapter as the chapter_items row.
create unique index if not exists courses_id_chapter_ordering_key
  on public.courses (id, chapter_id);

create unique index if not exists course_folders_id_chapter_ordering_key
  on public.course_folders (id, chapter_id);

create table if not exists public.chapter_items (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null,
  user_id uuid not null,
  course_id bigint null,
  folder_id bigint null,
  position integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),

  constraint chapter_items_one_target_check check (
    (course_id is not null)::integer +
    (folder_id is not null)::integer = 1
  ),
  constraint chapter_items_position_check check (position >= 0),
  constraint chapter_items_chapter_fk
    foreign key (chapter_id)
    references public.chapters(id)
    on delete cascade,
  constraint chapter_items_user_fk
    foreign key (user_id)
    references auth.users(id)
    on delete cascade,
  constraint chapter_items_course_fk
    foreign key (course_id)
    references public.courses(id)
    on delete cascade,
  constraint chapter_items_folder_fk
    foreign key (folder_id)
    references public.course_folders(id)
    on delete cascade,
  constraint chapter_items_course_chapter_fk
    foreign key (course_id, chapter_id)
    references public.courses(id, chapter_id)
    on delete cascade,
  constraint chapter_items_folder_chapter_fk
    foreign key (folder_id, chapter_id)
    references public.course_folders(id, chapter_id)
    on delete cascade,
  constraint chapter_items_unique_position
    unique (chapter_id, position),
  constraint chapter_items_unique_course
    unique (course_id),
  constraint chapter_items_unique_folder
    unique (folder_id)
);

alter table public.chapter_items enable row level security;

-- Existing courses and folders are represented independently. A course that
-- already belongs to a folder still receives its own chapter_items row.
with existing_items as (
  select
    course.chapter_id,
    chapter.user_id,
    course.id as course_id,
    null::bigint as folder_id,
    course.created_at,
    course.id as item_id
  from public.courses as course
  join public.chapters as chapter
    on chapter.id = course.chapter_id
  where chapter.user_id is not null

  union all

  select
    folder.chapter_id,
    chapter.user_id,
    null::bigint as course_id,
    folder.id as folder_id,
    folder.created_at,
    folder.id as item_id
  from public.course_folders as folder
  join public.chapters as chapter
    on chapter.id = folder.chapter_id
  where chapter.user_id is not null
), ranked_items as (
  select
    chapter_id,
    user_id,
    course_id,
    folder_id,
    row_number() over (
      partition by chapter_id
      order by created_at desc, item_id desc
    ) - 1 as next_position
  from existing_items
)
insert into public.chapter_items (
  chapter_id,
  user_id,
  course_id,
  folder_id,
  position
)
select
  ranked.chapter_id,
  ranked.user_id,
  ranked.course_id,
  ranked.folder_id,
  ranked.next_position
from ranked_items as ranked
where not exists (
  select 1
  from public.chapter_items as current_item
  where (ranked.course_id is not null and current_item.course_id = ranked.course_id)
     or (ranked.folder_id is not null and current_item.folder_id = ranked.folder_id)
);

create policy "chapter_items_select_own"
on public.chapter_items
for select
using (
  auth.uid() = chapter_items.user_id
  and exists (
    select 1
    from public.chapters as chapter
    where chapter.id = chapter_items.chapter_id
      and chapter.user_id = auth.uid()
  )
  and (
    (
      chapter_items.course_id is not null
      and exists (
        select 1
        from public.courses as course
        where course.id = chapter_items.course_id
          and course.chapter_id = chapter_items.chapter_id
          and course.user_id = auth.uid()
      )
    )
    or
    (
      chapter_items.folder_id is not null
      and exists (
        select 1
        from public.course_folders as folder
        where folder.id = chapter_items.folder_id
          and folder.chapter_id = chapter_items.chapter_id
          and folder.user_id = auth.uid()
      )
    )
  )
);

create policy "chapter_items_insert_own"
on public.chapter_items
for insert
with check (
  auth.uid() = chapter_items.user_id
  and exists (
    select 1
    from public.chapters as chapter
    where chapter.id = chapter_items.chapter_id
      and chapter.user_id = auth.uid()
  )
  and (
    (
      chapter_items.course_id is not null
      and exists (
        select 1
        from public.courses as course
        where course.id = chapter_items.course_id
          and course.chapter_id = chapter_items.chapter_id
          and course.user_id = auth.uid()
      )
    )
    or
    (
      chapter_items.folder_id is not null
      and exists (
        select 1
        from public.course_folders as folder
        where folder.id = chapter_items.folder_id
          and folder.chapter_id = chapter_items.chapter_id
          and folder.user_id = auth.uid()
      )
    )
  )
);

create policy "chapter_items_update_own"
on public.chapter_items
for update
using (
  auth.uid() = chapter_items.user_id
)
with check (
  auth.uid() = chapter_items.user_id
  and exists (
    select 1
    from public.chapters as chapter
    where chapter.id = chapter_items.chapter_id
      and chapter.user_id = auth.uid()
  )
  and (
    (
      chapter_items.course_id is not null
      and exists (
        select 1
        from public.courses as course
        where course.id = chapter_items.course_id
          and course.chapter_id = chapter_items.chapter_id
          and course.user_id = auth.uid()
      )
    )
    or
    (
      chapter_items.folder_id is not null
      and exists (
        select 1
        from public.course_folders as folder
        where folder.id = chapter_items.folder_id
          and folder.chapter_id = chapter_items.chapter_id
          and folder.user_id = auth.uid()
      )
    )
  )
);

create policy "chapter_items_delete_own"
on public.chapter_items
for delete
using (
  auth.uid() = chapter_items.user_id
  and exists (
    select 1
    from public.chapters as chapter
    where chapter.id = chapter_items.chapter_id
      and chapter.user_id = auth.uid()
  )
);
