create table if not exists public.planning_years (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Année scolaire',
  starts_on date not null,
  ends_on date not null,
  time_zone text not null default 'UTC',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planning_years_date_order check (starts_on <= ends_on),
  constraint planning_years_id_user_key unique (id, user_id)
);

create table if not exists public.planning_calendar_blocks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  year_id bigint not null,
  kind text not null check (kind in ('break', 'holiday')),
  name text,
  starts_on date not null,
  ends_on date not null,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planning_calendar_blocks_date_order check (starts_on <= ends_on),
  constraint planning_calendar_blocks_holiday_date check (kind <> 'holiday' or starts_on = ends_on),
  constraint planning_calendar_blocks_year_user_fk
    foreign key (year_id, user_id)
    references public.planning_years(id, user_id)
    on delete cascade
);

create table if not exists public.planning_series (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  year_id bigint not null,
  entry_type text not null default 'class',
  title text not null,
  subject_id bigint references public.subjects(id) on delete set null,
  teacher text,
  room text,
  day_of_week smallint not null check (day_of_week between 1 and 7),
  recurrence text not null check (recurrence in ('weekly', 'once')),
  week_pattern text not null default 'all' check (week_pattern in ('all', 'even', 'odd')),
  starts_on date not null,
  ends_on date,
  start_time time not null,
  end_time time not null,
  color_key text,
  icon_key text,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planning_series_time_order check (start_time < end_time),
  constraint planning_series_recurrence_dates check (
    (recurrence = 'weekly' and ends_on is not null and starts_on <= ends_on)
    or (recurrence = 'once' and ends_on is null)
  ),
  constraint planning_series_year_user_fk
    foreign key (year_id, user_id)
    references public.planning_years(id, user_id)
    on delete cascade,
  constraint planning_series_id_user_key unique (id, user_id)
);

create table if not exists public.planning_exceptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  series_id bigint not null,
  occurrence_date date not null,
  status text not null check (status in ('cancelled', 'modified')),
  override_date date,
  overrides jsonb not null default '{}'::jsonb check (jsonb_typeof(overrides) = 'object'),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planning_exceptions_series_user_fk
    foreign key (series_id, user_id)
    references public.planning_series(id, user_id)
    on delete cascade,
  constraint planning_exceptions_unique_occurrence unique (series_id, occurrence_date)
);

create index if not exists planning_years_user_dates_idx
  on public.planning_years (user_id, starts_on desc);
create index if not exists planning_calendar_blocks_year_dates_idx
  on public.planning_calendar_blocks (year_id, starts_on, ends_on);
create index if not exists planning_series_year_schedule_idx
  on public.planning_series (year_id, day_of_week, start_time);
create index if not exists planning_exceptions_user_series_idx
  on public.planning_exceptions (user_id, series_id, occurrence_date);

create or replace function public.set_planning_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists planning_years_updated_at on public.planning_years;
create trigger planning_years_updated_at
before update on public.planning_years
for each row execute function public.set_planning_updated_at();
drop trigger if exists planning_calendar_blocks_updated_at on public.planning_calendar_blocks;
create trigger planning_calendar_blocks_updated_at
before update on public.planning_calendar_blocks
for each row execute function public.set_planning_updated_at();
drop trigger if exists planning_series_updated_at on public.planning_series;
create trigger planning_series_updated_at
before update on public.planning_series
for each row execute function public.set_planning_updated_at();
drop trigger if exists planning_exceptions_updated_at on public.planning_exceptions;
create trigger planning_exceptions_updated_at
before update on public.planning_exceptions
for each row execute function public.set_planning_updated_at();

create or replace function public.sync_planning_series_year_dates()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  school_year_start date;
  school_year_end date;
begin
  select school_year.starts_on, school_year.ends_on
  into school_year_start, school_year_end
  from public.planning_years as school_year
  where school_year.id = new.year_id
    and school_year.user_id = new.user_id;

  if school_year_start is null or school_year_end is null then
    raise exception 'Année scolaire inaccessible.' using errcode = '23503';
  end if;

  if new.recurrence = 'weekly' then
    new.starts_on := school_year_start;
    new.ends_on := school_year_end;
  elsif new.recurrence = 'once' then
    if new.starts_on < school_year_start or new.starts_on > school_year_end then
      raise exception 'La séance ponctuelle doit se trouver dans l’année scolaire.' using errcode = '23514';
    end if;
    new.ends_on := null;
  end if;

  return new;
end;
$$;

drop trigger if exists planning_series_sync_year_dates on public.planning_series;
create trigger planning_series_sync_year_dates
before insert or update of year_id, recurrence, starts_on, ends_on on public.planning_series
for each row execute function public.sync_planning_series_year_dates();

create or replace function public.sync_planning_year_series_dates()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.planning_series as series
    where series.year_id = new.id
      and series.user_id = new.user_id
      and series.recurrence = 'once'
      and (series.starts_on < new.starts_on or series.starts_on > new.ends_on)
  ) then
    raise exception 'Une séance ponctuelle se trouverait hors de la nouvelle année scolaire.' using errcode = '23514';
  end if;

  update public.planning_series as series
  set starts_on = new.starts_on,
      ends_on = new.ends_on
  where series.year_id = new.id
    and series.user_id = new.user_id
    and series.recurrence = 'weekly';

  return new;
end;
$$;

drop trigger if exists planning_years_sync_series_dates on public.planning_years;
create trigger planning_years_sync_series_dates
after update of starts_on, ends_on on public.planning_years
for each row execute function public.sync_planning_year_series_dates();

alter table public.planning_years enable row level security;
alter table public.planning_calendar_blocks enable row level security;
alter table public.planning_series enable row level security;
alter table public.planning_exceptions enable row level security;

drop policy if exists planning_years_select_own on public.planning_years;
drop policy if exists planning_years_insert_own on public.planning_years;
drop policy if exists planning_years_update_own on public.planning_years;
drop policy if exists planning_years_delete_own on public.planning_years;
create policy planning_years_select_own on public.planning_years
for select using (auth.uid() = user_id);
create policy planning_years_insert_own on public.planning_years
for insert with check (auth.uid() = user_id);
create policy planning_years_update_own on public.planning_years
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy planning_years_delete_own on public.planning_years
for delete using (auth.uid() = user_id);

drop policy if exists planning_calendar_blocks_select_own on public.planning_calendar_blocks;
drop policy if exists planning_calendar_blocks_insert_own on public.planning_calendar_blocks;
drop policy if exists planning_calendar_blocks_update_own on public.planning_calendar_blocks;
drop policy if exists planning_calendar_blocks_delete_own on public.planning_calendar_blocks;
create policy planning_calendar_blocks_select_own on public.planning_calendar_blocks
for select using (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_calendar_blocks.year_id and school_year.user_id = auth.uid()
  )
);
create policy planning_calendar_blocks_insert_own on public.planning_calendar_blocks
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_calendar_blocks.year_id and school_year.user_id = auth.uid()
  )
);
create policy planning_calendar_blocks_update_own on public.planning_calendar_blocks
for update using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_calendar_blocks.year_id and school_year.user_id = auth.uid()
  )
);
create policy planning_calendar_blocks_delete_own on public.planning_calendar_blocks
for delete using (auth.uid() = user_id);

drop policy if exists planning_series_select_own on public.planning_series;
drop policy if exists planning_series_insert_own on public.planning_series;
drop policy if exists planning_series_update_own on public.planning_series;
drop policy if exists planning_series_delete_own on public.planning_series;
create policy planning_series_select_own on public.planning_series
for select using (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_series.year_id and school_year.user_id = auth.uid()
  )
  and (
    subject_id is null
    or exists (
      select 1 from public.subjects as subject
      where subject.id = planning_series.subject_id and subject.user_id = auth.uid()
    )
  )
);
create policy planning_series_insert_own on public.planning_series
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_series.year_id and school_year.user_id = auth.uid()
  )
  and (
    subject_id is null
    or exists (
      select 1 from public.subjects as subject
      where subject.id = planning_series.subject_id and subject.user_id = auth.uid()
    )
  )
);
create policy planning_series_update_own on public.planning_series
for update using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_years as school_year
    where school_year.id = planning_series.year_id and school_year.user_id = auth.uid()
  )
  and (
    subject_id is null
    or exists (
      select 1 from public.subjects as subject
      where subject.id = planning_series.subject_id and subject.user_id = auth.uid()
    )
  )
);
create policy planning_series_delete_own on public.planning_series
for delete using (auth.uid() = user_id);

drop policy if exists planning_exceptions_select_own on public.planning_exceptions;
drop policy if exists planning_exceptions_insert_own on public.planning_exceptions;
drop policy if exists planning_exceptions_update_own on public.planning_exceptions;
drop policy if exists planning_exceptions_delete_own on public.planning_exceptions;
create policy planning_exceptions_select_own on public.planning_exceptions
for select using (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_series as series
    where series.id = planning_exceptions.series_id and series.user_id = auth.uid()
  )
);
create policy planning_exceptions_insert_own on public.planning_exceptions
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_series as series
    where series.id = planning_exceptions.series_id and series.user_id = auth.uid()
  )
);
create policy planning_exceptions_update_own on public.planning_exceptions
for update using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.planning_series as series
    where series.id = planning_exceptions.series_id and series.user_id = auth.uid()
  )
);
create policy planning_exceptions_delete_own on public.planning_exceptions
for delete using (auth.uid() = user_id);