create table if not exists public.revision_questions (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  question_type text not null,
  question_text text not null,
  choices jsonb,
  explanation text,
  difficulty text not null default 'medium',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint revision_questions_course_fk
    foreign key (course_id) references public.courses(id) on delete cascade,
  constraint revision_questions_type_check
    check (question_type in ('multiple_choice', 'true_false', 'short_answer')),
  constraint revision_questions_difficulty_check
    check (difficulty in ('easy', 'medium', 'hard')),
  constraint revision_questions_position_check
    check (position >= 0),
  constraint revision_questions_choices_check
    check (
      (question_type = 'multiple_choice'
        and choices is not null
        and jsonb_typeof(choices) = 'array')
      or (question_type in ('true_false', 'short_answer') and choices is null)
    )
);

create table if not exists public.revision_question_keys (
  question_id bigint primary key,
  correct_answer jsonb not null,
  constraint revision_question_keys_question_fk
    foreign key (question_id)
    references public.revision_questions(id)
    on delete cascade
);

create table if not exists public.revision_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  course_id bigint,
  question_ids_snapshot bigint[] not null,
  status text not null,
  total_questions integer not null,
  correct_answers integer not null,
  score numeric(5, 2) not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_seconds integer,
  created_at timestamptz not null default now(),
  constraint revision_sessions_user_fk
    foreign key (user_id) references auth.users(id) on delete cascade,
  constraint revision_sessions_course_fk
    foreign key (course_id) references public.courses(id) on delete set null,
  constraint revision_sessions_status_check
    check (status in ('in_progress', 'completed', 'abandoned')),
  constraint revision_sessions_counts_check
    check (
      total_questions >= 0
      and correct_answers >= 0
      and correct_answers <= total_questions
      and total_questions = cardinality(question_ids_snapshot)
      and array_position(question_ids_snapshot, null) is null
    ),
  constraint revision_sessions_score_check
    check (
      score between 0 and 100
      and score = case
        when total_questions = 0 then 0::numeric
        else round(correct_answers::numeric * 100 / total_questions, 2)
      end
    ),
  constraint revision_sessions_duration_check
    check (duration_seconds is null or duration_seconds >= 0),
  constraint revision_sessions_terminal_time_check
    check (
      (status = 'in_progress' and completed_at is null and duration_seconds is null)
      or (status in ('completed', 'abandoned')
        and completed_at is not null
        and duration_seconds is not null)
    )
);

create table if not exists public.revision_answers (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  question_id bigint,
  question_text_snapshot text not null,
  question_type_snapshot text not null,
  choices_snapshot jsonb,
  answer jsonb not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now(),
  constraint revision_answers_session_fk
    foreign key (session_id)
    references public.revision_sessions(id)
    on delete cascade,
  constraint revision_answers_question_fk
    foreign key (question_id)
    references public.revision_questions(id)
    on delete set null,
  constraint revision_answers_type_check
    check (question_type_snapshot in ('multiple_choice', 'true_false', 'short_answer')),
  constraint revision_answers_choices_check
    check (
      (question_type_snapshot = 'multiple_choice'
        and choices_snapshot is not null
        and jsonb_typeof(choices_snapshot) = 'array')
      or (question_type_snapshot in ('true_false', 'short_answer')
        and choices_snapshot is null)
    ),
  constraint revision_answers_session_question_key
    unique (session_id, question_id)
);

create index if not exists revision_questions_course_position_idx
  on public.revision_questions (course_id, position, id);
create index if not exists revision_sessions_user_started_idx
  on public.revision_sessions (user_id, started_at desc);
create index if not exists revision_sessions_course_idx
  on public.revision_sessions (course_id);
create index if not exists revision_answers_question_idx
  on public.revision_answers (question_id);

create or replace function public.set_revision_questions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

drop trigger if exists revision_questions_updated_at
  on public.revision_questions;
create trigger revision_questions_updated_at
before update on public.revision_questions
for each row execute function public.set_revision_questions_updated_at();

create or replace function public.start_revision_session(
  p_user_id uuid,
  p_course_id bigint
)
returns table (
  session_id bigint,
  course_id bigint,
  status text,
  total_questions integer,
  correct_answers integer,
  score numeric,
  started_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_question_ids bigint[];
  v_session public.revision_sessions%rowtype;
begin
  if p_user_id is null or p_course_id is null then
    raise exception 'Session de révision invalide.' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.courses as course
    join public.chapters as chapter on chapter.id = course.chapter_id
    join public.subjects as subject on subject.id = chapter.subject_id
    where course.id = p_course_id
      and course.user_id = p_user_id
      and chapter.user_id = p_user_id
      and subject.user_id = p_user_id
      and (
        course.folder_id is null
        or exists (
          select 1
          from public.course_folders as folder
          where folder.id = course.folder_id
            and folder.chapter_id = chapter.id
            and folder.user_id = p_user_id
        )
      )
  ) then
    raise exception 'Cours introuvable.' using errcode = 'P0002';
  end if;

  select coalesce(
    array_agg(question.id order by question.position, question.id),
    array[]::bigint[]
  )
  into v_question_ids
  from public.revision_questions as question
  where question.course_id = p_course_id;

  if cardinality(v_question_ids) = 0 then
    raise exception 'Ce cours ne contient aucune question.' using errcode = 'P0001';
  end if;

  insert into public.revision_sessions (
    user_id,
    course_id,
    question_ids_snapshot,
    status,
    total_questions,
    correct_answers,
    score,
    started_at
  )
  values (
    p_user_id,
    p_course_id,
    v_question_ids,
    'in_progress',
    cardinality(v_question_ids),
    0,
    0,
    pg_catalog.now()
  )
  returning * into v_session;

  return query
  select v_session.id,
         v_session.course_id,
         v_session.status,
         v_session.total_questions,
         v_session.correct_answers,
         v_session.score,
         v_session.started_at,
         v_session.created_at;
end;
$$;

create or replace function public.submit_revision_answer(
  p_user_id uuid,
  p_session_id bigint,
  p_question_id bigint,
  p_answer jsonb
)
returns table (
  is_correct boolean,
  answered_at timestamptz,
  correct_answers integer,
  total_questions integer,
  score numeric
)
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_session public.revision_sessions%rowtype;
  v_question public.revision_questions%rowtype;
  v_correct_answer jsonb;
  v_is_correct boolean;
  v_answered_at timestamptz := pg_catalog.now();
  v_correct_count integer;
  v_score numeric(5, 2);
  v_answer_text text;
  v_correct_text text;
begin
  select session.*
  into v_session
  from public.revision_sessions as session
  where session.id = p_session_id
    and session.user_id = p_user_id
  for update;

  if not found then
    raise exception 'Session introuvable.' using errcode = 'P0002';
  end if;
  if v_session.status <> 'in_progress' then
    raise exception 'La session est déjà terminée.' using errcode = '55000';
  end if;
  if p_question_id is null
     or not (p_question_id = any(v_session.question_ids_snapshot)) then
    raise exception 'Question introuvable dans cette session.' using errcode = 'P0002';
  end if;

  select question.*
  into v_question
  from public.revision_questions as question
  where question.id = p_question_id
    and question.course_id = v_session.course_id
  for share of question;
  if not found or v_session.course_id is null then
    raise exception 'Question introuvable dans cette session.' using errcode = 'P0002';
  end if;

  if not exists (
    select 1
    from public.courses as course
    join public.chapters as chapter on chapter.id = course.chapter_id
    join public.subjects as subject on subject.id = chapter.subject_id
    where course.id = v_session.course_id
      and course.user_id = p_user_id
      and chapter.user_id = p_user_id
      and subject.user_id = p_user_id
      and (
        course.folder_id is null
        or exists (
          select 1
          from public.course_folders as folder
          where folder.id = course.folder_id
            and folder.chapter_id = chapter.id
            and folder.user_id = p_user_id
        )
      )
  ) then
    raise exception 'Cours introuvable.' using errcode = 'P0002';
  end if;

  select question_key.correct_answer
  into v_correct_answer
  from public.revision_question_keys as question_key
  where question_key.question_id = v_question.id;
  if not found then
    raise exception 'Clé de correction indisponible.' using errcode = 'P0002';
  end if;

  case v_question.question_type
    when 'multiple_choice' then
      if jsonb_typeof(p_answer) is distinct from 'string'
         or not exists (
           select 1
           from jsonb_array_elements(v_question.choices) as option_value(value)
           where option_value.value ->> 'id' = p_answer #>> '{}'
         ) then
        raise exception 'Réponse QCM invalide.' using errcode = '22023';
      end if;
      v_is_correct := p_answer = v_correct_answer;
    when 'true_false' then
      if jsonb_typeof(p_answer) is distinct from 'boolean' then
        raise exception 'Réponse vrai/faux invalide.' using errcode = '22023';
      end if;
      v_is_correct := p_answer = v_correct_answer;
    when 'short_answer' then
      if jsonb_typeof(p_answer) is distinct from 'string'
         or jsonb_typeof(v_correct_answer) is distinct from 'string' then
        raise exception 'Réponse courte invalide.' using errcode = '22023';
      end if;
      v_answer_text := pg_catalog.lower(
        pg_catalog.regexp_replace(pg_catalog.btrim(p_answer #>> '{}'), '[[:space:]]+', ' ', 'g')
      );
      v_correct_text := pg_catalog.lower(
        pg_catalog.regexp_replace(pg_catalog.btrim(v_correct_answer #>> '{}'), '[[:space:]]+', ' ', 'g')
      );
      v_is_correct := v_answer_text = v_correct_text;
    else
      raise exception 'Type de question invalide.' using errcode = '22023';
  end case;

  insert into public.revision_answers (
    session_id,
    question_id,
    question_text_snapshot,
    question_type_snapshot,
    choices_snapshot,
    answer,
    is_correct,
    answered_at
  )
  values (
    v_session.id,
    v_question.id,
    v_question.question_text,
    v_question.question_type,
    case when v_question.question_type = 'multiple_choice' then v_question.choices else null end,
    p_answer,
    v_is_correct,
    v_answered_at
  );

  select count(*) filter (where revision_answer.is_correct)::integer
  into v_correct_count
  from public.revision_answers as revision_answer
  where revision_answer.session_id = v_session.id;

  v_score := round(v_correct_count::numeric * 100 / v_session.total_questions, 2);

  update public.revision_sessions as session
  set correct_answers = v_correct_count,
      score = v_score
  where session.id = v_session.id
  returning session.correct_answers, session.total_questions, session.score
  into v_correct_count, total_questions, v_score;

  return query
  select v_is_correct, v_answered_at, v_correct_count, total_questions, v_score;
end;
$$;

create or replace function public.close_revision_session(
  p_user_id uuid,
  p_session_id bigint,
  p_status text
)
returns table (
  session_id bigint,
  course_id bigint,
  status text,
  total_questions integer,
  correct_answers integer,
  score numeric,
  started_at timestamptz,
  completed_at timestamptz,
  duration_seconds integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_session public.revision_sessions%rowtype;
  v_completed_at timestamptz := pg_catalog.now();
begin
  if p_status is null or p_status not in ('completed', 'abandoned') then
    raise exception 'Statut de clôture invalide.' using errcode = '22023';
  end if;

  select session.*
  into v_session
  from public.revision_sessions as session
  where session.id = p_session_id
    and session.user_id = p_user_id
  for update;

  if not found then
    raise exception 'Session introuvable.' using errcode = 'P0002';
  end if;
  if v_session.status <> 'in_progress' then
    raise exception 'La session est déjà terminée.' using errcode = '55000';
  end if;

  update public.revision_sessions as session
  set status = p_status,
      completed_at = v_completed_at,
      duration_seconds = greatest(
        0,
        floor(extract(epoch from (v_completed_at - session.started_at)))::integer
      )
  where session.id = v_session.id
  returning session.* into v_session;

  return query
  select v_session.id,
         v_session.course_id,
         v_session.status,
         v_session.total_questions,
         v_session.correct_answers,
         v_session.score,
         v_session.started_at,
         v_session.completed_at,
         v_session.duration_seconds,
         v_session.created_at;
end;
$$;

create or replace function public.save_revision_question(
  p_user_id uuid,
  p_course_id bigint,
  p_question_id bigint,
  p_question_type text,
  p_question_text text,
  p_choices jsonb,
  p_explanation text,
  p_difficulty text,
  p_position integer,
  p_correct_answer jsonb
)
returns public.revision_questions
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_question public.revision_questions%rowtype;
  v_choice_count integer;
  v_distinct_choice_count integer;
begin
  if not exists (
    select 1
    from public.courses as course
    join public.chapters as chapter on chapter.id = course.chapter_id
    join public.subjects as subject on subject.id = chapter.subject_id
    where course.id = p_course_id
      and course.user_id = p_user_id
      and chapter.user_id = p_user_id
      and subject.user_id = p_user_id
      and (
        course.folder_id is null
        or exists (
          select 1
          from public.course_folders as folder
          where folder.id = course.folder_id
            and folder.chapter_id = chapter.id
            and folder.user_id = p_user_id
        )
      )
  ) then
    raise exception 'Cours introuvable.' using errcode = 'P0002';
  end if;

  if p_question_type = 'multiple_choice' then
    if jsonb_typeof(p_choices) is distinct from 'array' then
      raise exception 'Les choix du QCM sont invalides.' using errcode = '22023';
    end if;
    if jsonb_array_length(p_choices) < 2 then
      raise exception 'Les choix du QCM sont invalides.' using errcode = '22023';
    end if;
    select count(*)::integer, count(distinct choice.value ->> 'id')::integer
    into v_choice_count, v_distinct_choice_count
    from jsonb_array_elements(p_choices) as choice(value)
    where jsonb_typeof(choice.value) = 'object'
      and choice.value ->> 'id' is not null
      and choice.value ->> 'text' is not null;
    if v_choice_count <> jsonb_array_length(p_choices)
       or v_distinct_choice_count <> v_choice_count
       or jsonb_typeof(p_correct_answer) is distinct from 'string'
       or not exists (
         select 1
         from jsonb_array_elements(p_choices) as choice(value)
         where choice.value ->> 'id' = p_correct_answer #>> '{}'
       ) then
      raise exception 'Les choix ou la correction du QCM sont invalides.' using errcode = '22023';
    end if;
  elsif p_question_type = 'true_false' then
    if p_choices is not null or jsonb_typeof(p_correct_answer) is distinct from 'boolean' then
      raise exception 'La correction vrai/faux est invalide.' using errcode = '22023';
    end if;
  elsif p_question_type = 'short_answer' then
    if p_choices is not null or jsonb_typeof(p_correct_answer) is distinct from 'string' then
      raise exception 'La correction de réponse courte est invalide.' using errcode = '22023';
    end if;
  else
    raise exception 'Type de question invalide.' using errcode = '22023';
  end if;

  if p_difficulty not in ('easy', 'medium', 'hard') or p_position < 0 then
    raise exception 'Difficulté ou position invalide.' using errcode = '22023';
  end if;

  if p_question_id is null then
    insert into public.revision_questions (
      course_id, question_type, question_text, choices, explanation, difficulty, position
    )
    values (
      p_course_id, p_question_type, p_question_text, p_choices,
      p_explanation, p_difficulty, p_position
    )
    returning * into v_question;
  else
    select question.*
    into v_question
    from public.revision_questions as question
    where question.id = p_question_id
      and question.course_id = p_course_id
    for update;
    if not found then
      raise exception 'Question introuvable.' using errcode = 'P0002';
    end if;

    update public.revision_questions as question
    set question_type = p_question_type,
        question_text = p_question_text,
        choices = p_choices,
        explanation = p_explanation,
        difficulty = p_difficulty,
        position = p_position
    where question.id = p_question_id
    returning question.* into v_question;
  end if;

  insert into public.revision_question_keys (question_id, correct_answer)
  values (v_question.id, p_correct_answer)
  on conflict (question_id) do update
    set correct_answer = excluded.correct_answer;

  return v_question;
end;
$$;

create or replace function public.delete_revision_question(
  p_user_id uuid,
  p_question_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_question_course_id bigint;
begin
  select question.course_id
  into v_question_course_id
  from public.revision_questions as question
  join public.courses as course on course.id = question.course_id
  join public.chapters as chapter on chapter.id = course.chapter_id
  join public.subjects as subject on subject.id = chapter.subject_id
  where question.id = p_question_id
    and course.user_id = p_user_id
    and chapter.user_id = p_user_id
    and subject.user_id = p_user_id
    and (
      course.folder_id is null
      or exists (
        select 1
        from public.course_folders as folder
        where folder.id = course.folder_id
          and folder.chapter_id = chapter.id
          and folder.user_id = p_user_id
      )
    )
  for update of question;

  if not found then
    raise exception 'Question introuvable.' using errcode = 'P0002';
  end if;

  delete from public.revision_questions as question
  where question.id = p_question_id;
end;
$$;

alter table public.revision_questions enable row level security;
alter table public.revision_question_keys enable row level security;
alter table public.revision_sessions enable row level security;
alter table public.revision_answers enable row level security;

drop policy if exists revision_questions_select_own on public.revision_questions;
create policy revision_questions_select_own
on public.revision_questions for select to authenticated
using (
  exists (
    select 1
    from public.courses as course
    join public.chapters as chapter on chapter.id = course.chapter_id
    join public.subjects as subject on subject.id = chapter.subject_id
    where course.id = revision_questions.course_id
      and course.user_id = auth.uid()
      and chapter.user_id = auth.uid()
      and subject.user_id = auth.uid()
      and (
        course.folder_id is null
        or exists (
          select 1
          from public.course_folders as folder
          where folder.id = course.folder_id
            and folder.chapter_id = chapter.id
            and folder.user_id = auth.uid()
        )
      )
  )
);

drop policy if exists revision_sessions_select_own on public.revision_sessions;
create policy revision_sessions_select_own
on public.revision_sessions for select to authenticated
using (user_id = auth.uid());

drop policy if exists revision_answers_select_own on public.revision_answers;
create policy revision_answers_select_own
on public.revision_answers for select to authenticated
using (
  exists (
    select 1
    from public.revision_sessions as session
    where session.id = revision_answers.session_id
      and session.user_id = auth.uid()
  )
);

revoke all on table public.revision_questions from anon, authenticated;
revoke all on table public.revision_question_keys from anon, authenticated;
revoke all on table public.revision_sessions from anon, authenticated;
revoke all on table public.revision_answers from anon, authenticated;

grant select on table public.revision_questions to authenticated;
grant select on table public.revision_sessions to authenticated;
grant select on table public.revision_answers to authenticated;

revoke all on function public.start_revision_session(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.start_revision_session(uuid, bigint)
  to service_role;

revoke all on function public.submit_revision_answer(uuid, bigint, bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.submit_revision_answer(uuid, bigint, bigint, jsonb)
  to service_role;

revoke all on function public.close_revision_session(uuid, bigint, text)
  from public, anon, authenticated;
grant execute on function public.close_revision_session(uuid, bigint, text)
  to service_role;

revoke all on function public.save_revision_question(
  uuid, bigint, bigint, text, text, jsonb, text, text, integer, jsonb
) from public, anon, authenticated;
grant execute on function public.save_revision_question(
  uuid, bigint, bigint, text, text, jsonb, text, text, integer, jsonb
) to service_role;

revoke all on function public.delete_revision_question(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.delete_revision_question(uuid, bigint)
  to service_role;

revoke all on function public.set_revision_questions_updated_at()
  from public, anon, authenticated;